// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR_7CnFp4yM_TIaQCS7YLAyLMVQOddVGw',
    appId: '1:1010606656870:web:9cb619cbf31697dec18ca7',
    messagingSenderId: '1010606656870',
    projectId: 'grocery-list-app-c59d7',
    authDomain: 'grocery-list-app-c59d7.firebaseapp.com',
    storageBucket: 'grocery-list-app-c59d7.firebasestorage.app',
    measurementId: 'G-51VLPE24HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPH-eSP1ZfGqY4bzBdGPqluUL99voOm-Y',
    appId: '1:1010606656870:android:a6ce41403dc228d2c18ca7',
    messagingSenderId: '1010606656870',
    projectId: 'grocery-list-app-c59d7',
    storageBucket: 'grocery-list-app-c59d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAANpAdl-h_BYN_DemjTbSsPNLt4wAsGQ0',
    appId: '1:1010606656870:ios:61421d7e6d640f3dc18ca7',
    messagingSenderId: '1010606656870',
    projectId: 'grocery-list-app-c59d7',
    storageBucket: 'grocery-list-app-c59d7.firebasestorage.app',
    iosBundleId: 'com.example.grocerylistapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAANpAdl-h_BYN_DemjTbSsPNLt4wAsGQ0',
    appId: '1:1010606656870:ios:61421d7e6d640f3dc18ca7',
    messagingSenderId: '1010606656870',
    projectId: 'grocery-list-app-c59d7',
    storageBucket: 'grocery-list-app-c59d7.firebasestorage.app',
    iosBundleId: 'com.example.grocerylistapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR_7CnFp4yM_TIaQCS7YLAyLMVQOddVGw',
    appId: '1:1010606656870:web:9cb619cbf31697dec18ca7',
    messagingSenderId: '1010606656870',
    projectId: 'grocery-list-app-c59d7',
    authDomain: 'grocery-list-app-c59d7.firebaseapp.com',
    storageBucket: 'grocery-list-app-c59d7.firebasestorage.app',
    measurementId: 'G-51VLPE24HT',
  );
}
